### ISSUE TITLE
net-ldap requires Ruby version >= 2.0.0

### ISSUE THREAD

**Issue by pescobar** [vincentvdk/ansible_pb_opennebula#1]
I did a test run of this playbook and I got this error when trying to deploy the management machine in centos 6.7

```
ERROR:  Error installing net-ldap:
        net-ldap requires Ruby version >= 2.0.0.
```

which is the recommended/supported `net-ldap` version?

thanks.

**Comment by pescobar** [comment]
I noticed this was written for an older OpenNebula version so I wrote my own ansible playbook to deploy latest OpenNebula 4.14 in centos7 https://github.com/pescobar/ansible-opennebula

closing this issue.

**Comment by vincentvdk** [comment]
Hi @pescobar. Sorry for the late reply.
I'm currently not maintaining an Opennebula setup anymore which is the reason this repo hasn't been updated anymore. Good that you were able to find a solution and I hope this repo has been helpful.
Thanks
